# Generated by Django 4.1 on 2022-08-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.FileField(default=22, upload_to='video/'),
            preserve_default=False,
        ),
    ]
